### ISSUE TITLE
自動デプロイの更新

### ISSUE THREAD

**Issue by minarin0179** [minarin0179/Madaminalink_v2#9]
サーバーをお引越しした関係で自動デプロイが死んでる
サーバーのsshの設定がまだ済んでないのでそれがすんだら直す

**Comment by minarin0179** [comment]
現状自宅サーバーのIPの公開設定ができていない
安いVPSを踏み台にしてリバースsshで繋げばつなげはすると思う

普通にhooks使ったほうが早い気がしている

**Comment by minarin0179** [comment]
self hosted runnerを使ったやり方だとSSH鍵を渡さなくていいので良さそう

参考資料
- https://zenn.dev/techno_tanoc/articles/445ec2150e6839
- https://zenn.dev/hironobuu/articles/e85418948e896f
- https://zenn.dev/hironobuu/articles/e85418948e896f

**Comment by fjktkm** [comment]
参考資料：

https://github.com/nitmic-git/nitmic.club.nitech.ac.jp/blob/main/.github/workflows/hugo.yml
